# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://139.224.67.165:11006/esfile?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: hujianlin
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: 139.224.67.165
    port: 11001
    password: hujianlin
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 0
        max-wait: -1ms
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 139.224.67.165:11015
      username: elastic
      password: hujianlin

# MinIO配置
minio:
  endpoint: http://139.224.67.165:11004
  access-key: hujianlin
  secret-key: hujianlin
  bucket: elasticsearch

# JWT配置
jwt:
  secret: esfile-dev-secret-key-2024
  expiration: 86400000
  header: Authorization

# 文件上传配置
file:
  upload:
    max-size: -1
    chunk-size: 1048576
    temp-dir: /tmp/upload

# 日志配置
logging:
  level:
    com.esfile: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
  file:
    name: logs/esfile-backend-dev.log

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
