# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  application:
    name: esfile-backend
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.esfile.entity
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 存储策略配置
storage:
  path-template: "files/{userId}/{year}/{month}/{day}/{filename}"
  deduplication: true
  compression: false
  encryption: false
  retention-days: 3650  # 10年
  versioning: true
  max-versions: 5

# 文件上传配置（dev环境没有的配置）
file:
  upload:
    allowed-types: jpg,jpeg,png,gif,bmp,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar,7z,mp4,avi,mov,mp3,wav
    chunk-concurrency: 3


